#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define LAYER_LOCK_IDLE_TIMEOUT 60000
#define NO_AUTO_SHIFT_ALPHA
#define RETRO_SHIFT
