#pragma once

#define RGB_MATRIX_TIMEOUT 300000
#define RGB_MATRIX_SLEEP

#define CHORDAL_HOLD
#define TAPPING_TERM 250
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define FLOW_TAP_TERM 150
#define SPECULATIVE_HOLD

#define ONESHOT_TIMEOUT 5000

#define NO_AUTO_SHIFT_SYMBOLS
#define NO_AUTO_SHIFT_NUMERIC
#define NO_AUTO_SHIFT_ALPHA
#define RETRO_SHIFT 300

#define COMBO_TERM 35
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_ONLY_FROM_LAYER 0

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define LAYER_LOCK_IDLE_TIMEOUT 60000

#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RIGHT_CTRL
#define MODS_TO_NEUTRALIZE {MOD_BIT(KC_LEFT_ALT), MOD_BIT(KC_LEFT_GUI), MOD_BIT(KC_RIGHT_GUI)}